### ISSUE TITLE
Support for Javalin 4.x

### ISSUE THREAD

**Issue by fedxyz** [kmehrunes/javalin-jwt#8]
Hi,

do you plan to support in the future Javalin 4.x ?
Right now I am not able to run your module with this version, some classes changed name/package.

Thanks

**Comment by kmehrunes** [comment]
Sure. I can give it a go soon, but can't promise a fast result as I'm a bit busy these days.

**Comment by fedxyz** [comment]
Thanks, no problem for the time, when it will be ready.
Nice it will be updated, I use your extension and I find it very simple to manage jwt token and javalin with it.

**Comment by kmehrunes** [comment]
Thanks @fedxyz, I'm glad to hear that.

**Comment by kmehrunes** [comment]
The changes are now on a test branch called javalin-4.x, could you please try it out and let me know if you had any issues?

**Comment by fedxyz** [comment]
I am sorry but I am unable to test it right now with javalin 4.x.

My project that use your extension is on 3.x release and upgrading on 4.x involves several changes that now I have no time to do, it's something that I have planned to do in near future but I can't now.

**Comment by kmehrunes** [comment]
The change is now complete and the examples run as expected. I'll create a release in a week or so, but feel free to test it out before that.

**Comment by fedxyz** [comment]
Hi,
I was finally able to test it using javalin 4 on my project.

I used this build with gradle:
`'com.github.kmehrunes:javalin-jwt:759b0ceb26'`

It works fine! like before, I had no issues with it.

For sure I will test more now that I am converting all my project to v4 and in case I will report.

Thanks for your help.

**Comment by fedxyz** [comment]
Just to add a note, if it is possible, when you will create a release for it to keep the compatibility with java 8.

**Comment by kmehrunes** [comment]
Thanks for trying it out @fedxyz, did you have problems using it with java 8? The module part shouldn't have affected compatibility with java 8, if it did then please let me know to fix it

**Comment by fedxyz** [comment]
Hi,

this is the stacktrace when I try to run with java 8, hope it will help.

```
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.UnsupportedClassVersionError: javalinjwt/JWTGenerator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at timbraweb_service.TimbrawebService.buildJWTProvider(TimbrawebService.java:205)
	at timbraweb_service.TimbrawebService.main(TimbrawebService.java:84)
Caused by: java.lang.UnsupportedClassVersionError: javalinjwt/JWTGenerator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

**Comment by kmehrunes** [comment]
I see. It's probably because of the target framework in the pom. I'll see if it's possible to support both.
